import FWCore.ParameterSet.Config as cms

from ..modules.goodOfflinePrimaryVertices_cfi import *
from ..modules.hlt1PFPuppiCentralJet70MaxEta2p4_cfi import *
from ..modules.hlt2PFPuppiCentralJet40MaxEta2p4_cfi import *
from ..modules.hltBTagPFPuppiDeepFlavour0p375Eta2p4TripleEta2p4_cfi import *
from ..modules.hltPFPuppiCentralJetQuad30MaxEta2p4_cfi import *
from ..modules.hltPFPuppiCentralJetsQuad30HT200MaxEta2p4_cfi import *
from ..modules.hltPFPuppiJetForBtagSelectorEta2p4_cfi import *
from ..modules.l1t1PFPuppiJet70offMaxEta2p4_cfi import *
from ..modules.l1t2PFPuppiJet55offMaxEta2p4_cfi import *
from ..modules.l1t4PFPuppiJet25OnlineMaxEta2p4_cfi import *
from ..modules.l1t4PFPuppiJet40offMaxEta2p4_cfi import *
from ..modules.l1tPFPuppiHT400offMaxEta2p4_cfi import *
from ..modules.ak4CaloJetsForTrk_cfi import *
from ..modules.bmtfDigis_cfi import *
from ..modules.bunchSpacingProducer_cfi import *
from ..modules.caloLayer1Digis_cfi import *
from ..modules.caloStage1Digis_cfi import *
from ..modules.caloStage1FinalDigis_cfi import *
from ..modules.caloStage1LegacyFormatDigis_cfi import *
from ..modules.caloStage2Digis_cfi import *
from ..modules.caloTowerForTrk_cfi import *
from ..modules.cleanedHybridSuperClusters_cfi import *
from ..modules.clusterSummaryProducer_cfi import *
from ..modules.correctedHybridSuperClusters_cfi import *
from ..modules.correctedMulti5x5SuperClustersWithPreshower_cfi import *
from ..modules.csctfDigis_cfi import *
from ..modules.ctppsDiamondRawToDigi_cfi import *
from ..modules.ctppsPixelDigis_cfi import *
from ..modules.dttfDigis_cfi import *
from ..modules.ecalBarrelClusterFastTimer_cfi import *
from ..modules.ecalCompactTrigPrim_cfi import *
from ..modules.ecalDetailedTimeRecHit_cfi import *
from ..modules.ecalDetIdToBeRecovered_cfi import *
from ..modules.ecalDigis_cfi import *
from ..modules.ecalMultiFitUncalibRecHit_cfi import *
from ..modules.ecalPreshowerDigis_cfi import *
from ..modules.ecalPreshowerRecHit_cfi import *
from ..modules.ecalRecHit_cfi import *
from ..modules.ecalTPSkim_cfi import *
from ..modules.emtfStage2Digis_cfi import *
from ..modules.filteredLayerClustersEM_cfi import *
from ..modules.filteredLayerClustersHAD_cfi import *
from ..modules.filteredLayerClustersTrk_cfi import *
from ..modules.filteredLayerClustersTrkEM_cfi import *
from ..modules.firstStepPrimaryVertices_cfi import *
from ..modules.firstStepPrimaryVerticesUnsorted_cfi import *
from ..modules.fixedGridRhoFastjetAllTmp_cfi import *
from ..modules.gctDigis_cfi import *
from ..modules.generalTracks_cfi import *
from ..modules.gmtStage2Digis_cfi import *
from ..modules.gtDigis_cfi import *
from ..modules.gtStage2Digis_cfi import *
from ..modules.hbhereco_cfi import *
from ..modules.hcalDigis_cfi import *
from ..modules.hfprereco_cfi import *
from ..modules.hfreco_cfi import *
from ..modules.hgcalDigis_cfi import *
from ..modules.hgcalLayerClusters_cfi import *
from ..modules.hgcalMultiClusters_cfi import *
from ..modules.HGCalRecHit_cfi import *
from ..modules.hgcalTrackCollection_cfi import *
from ..modules.HGCalUncalibRecHit_cfi import *
from ..modules.highPtTripletStepClusters_cfi import *
from ..modules.highPtTripletStepHitDoublets_cfi import *
from ..modules.highPtTripletStepHitTriplets_cfi import *
from ..modules.highPtTripletStepSeedLayers_cfi import *
from ..modules.highPtTripletStepSeeds_cfi import *
from ..modules.highPtTripletStepTrackCandidates_cfi import *
from ..modules.highPtTripletStepTrackCutClassifier_cfi import *
from ..modules.highPtTripletStepTrackingRegions_cfi import *
from ..modules.highPtTripletStepTracks_cfi import *
from ..modules.highPtTripletStepTrackSelectionHighPurity_cfi import *
from ..modules.hltAK4CaloJets_cfi import *
from ..modules.hltAK4PFPuppiJetCorrector_cfi import *
from ..modules.hltAK4PFPuppiJetCorrectorL1_cfi import *
from ..modules.hltAK4PFPuppiJetCorrectorL2_cfi import *
from ..modules.hltAK4PFPuppiJetCorrectorL3_cfi import *
from ..modules.hltAK4PFPuppiJets_cfi import *
from ..modules.hltAK4PFPuppiJetsCorrected_cfi import *
from ..modules.hltCsc2DRecHits_cfi import *
from ..modules.hltCscSegments_cfi import *
from ..modules.hltDeepBLifetimeTagInfosPFPuppiModEta2p4_cfi import *
from ..modules.hltDeepCombinedSecondaryVertexBJetTagsInfosPuppiModEta2p4_cfi import *
from ..modules.hltDeepInclusiveMergedVerticesPF_cfi import *
from ..modules.hltDeepInclusiveSecondaryVerticesPF_cfi import *
from ..modules.hltDeepInclusiveVertexFinderPF_cfi import *
from ..modules.hltDeepSecondaryVertexTagInfosPFPuppiModEta2p4_cfi import *
from ..modules.hltDeepTrackVertexArbitratorPF_cfi import *
from ..modules.hltDt1DRecHits_cfi import *
from ..modules.hltDt4DSegments_cfi import *
from ..modules.hltGemRecHits_cfi import *
from ..modules.hltGemSegments_cfi import *
from ..modules.hltIter0Phase2L3FromL1TkMuonCkfTrackCandidates_cfi import *
from ..modules.hltIter0Phase2L3FromL1TkMuonCtfWithMaterialTracks_cfi import *
from ..modules.hltIter0Phase2L3FromL1TkMuonPixelSeedsFromPixelTracks_cfi import *
from ..modules.hltIter0Phase2L3FromL1TkMuonTrackCutClassifier_cfi import *
from ..modules.hltIter0Phase2L3FromL1TkMuonTrackSelectionHighPurity_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonCkfTrackCandidates_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonClustersRefRemoval_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonCtfWithMaterialTracks_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonMaskedMeasurementTrackerEvent_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonMerged_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonPixelClusterCheck_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonPixelHitDoublets_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonPixelHitTriplets_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonPixelLayerTriplets_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonPixelSeeds_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonTrackCutClassifier_cfi import *
from ..modules.hltIter2Phase2L3FromL1TkMuonTrackSelectionHighPurity_cfi import *
from ..modules.hltL2MuonFromL1TkMuonCandidates_cfi import *
from ..modules.hltL2MuonSeedsFromL1TkMuon_cfi import *
from ..modules.hltL2MuonsFromL1TkMuon_cfi import *
from ..modules.hltL2OfflineMuonSeeds_cfi import *
from ..modules.hltL3MuonsPhase2L3Links_cfi import *
from ..modules.hltL3MuonsPhase2L3OI_cfi import *
from ..modules.hltMe0RecHits_cfi import *
from ..modules.hltMe0Segments_cfi import *
from ..modules.hltPfDeepFlavourJetTagsModEta2p4_cfi import *
from ..modules.hltPfDeepFlavourTagInfosModEta2p4_cfi import *
from ..modules.hltPFPuppi_cfi import *
from ..modules.hltPFPuppiJetForBtagEta2p4_cfi import *
from ..modules.hltPhase2L3FromL1TkMuonPixelLayerQuadruplets_cfi import *
from ..modules.hltPhase2L3FromL1TkMuonPixelTracks_cfi import *
from ..modules.hltPhase2L3FromL1TkMuonPixelTracksHitDoublets_cfi import *
from ..modules.hltPhase2L3FromL1TkMuonPixelTracksHitQuadruplets_cfi import *
from ..modules.hltPhase2L3FromL1TkMuonPixelTracksTrackingRegions_cfi import *
from ..modules.hltPhase2L3FromL1TkMuonPixelVertices_cfi import *
from ..modules.hltPhase2L3FromL1TkMuonTrimmedPixelVertices_cfi import *
from ..modules.hltPhase2L3GlbMuon_cfi import *
from ..modules.hltPhase2L3MuonCandidates_cfi import *
from ..modules.hltPhase2L3MuonMerged_cfi import *
from ..modules.hltPhase2L3MuonPixelTracksFilter_cfi import *
from ..modules.hltPhase2L3MuonPixelTracksFitter_cfi import *
from ..modules.hltPhase2L3Muons_cfi import *
from ..modules.hltPhase2L3MuonsNoID_cfi import *
from ..modules.hltPhase2L3MuonTracks_cfi import *
from ..modules.hltPhase2L3OIL3MuonCandidates_cfi import *
from ..modules.hltPhase2L3OIL3Muons_cfi import *
from ..modules.hltPhase2L3OIL3MuonsLinksCombination_cfi import *
from ..modules.hltPhase2L3OIMuCtfWithMaterialTracks_cfi import *
from ..modules.hltPhase2L3OIMuonTrackCutClassifier_cfi import *
from ..modules.hltPhase2L3OIMuonTrackSelectionHighPurity_cfi import *
from ..modules.hltPhase2L3OISeedsFromL2Muons_cfi import *
from ..modules.hltPhase2L3OITrackCandidates_cfi import *
from ..modules.hltPixelClustersMultiplicity_cfi import *
from ..modules.hltPrimaryVertexAssociationModEta2p4_cfi import *
from ..modules.hltRpcRecHits_cfi import *
from ..modules.horeco_cfi import *
from ..modules.hybridSuperClusters_cfi import *
from ..modules.inclusiveSecondaryVertices_cfi import *
from ..modules.inclusiveVertexFinder_cfi import *
from ..modules.initialStepSeeds_cfi import *
from ..modules.initialStepTrackCandidates_cfi import *
from ..modules.initialStepTrackCutClassifier_cfi import *
from ..modules.initialStepTrackRefsForJets_cfi import *
from ..modules.initialStepTracks_cfi import *
from ..modules.initialStepTrackSelectionHighPurity_cfi import *
from ..modules.l1tPFPuppiHT_cfi import *
from ..modules.MeasurementTrackerEvent_cfi import *
from ..modules.multi5x5BasicClustersCleaned_cfi import *
from ..modules.multi5x5BasicClustersUncleaned_cfi import *
from ..modules.multi5x5PreshowerClusterShape_cfi import *
from ..modules.multi5x5SuperClusters_cfi import *
from ..modules.multi5x5SuperClustersCleaned_cfi import *
from ..modules.multi5x5SuperClustersUncleaned_cfi import *
from ..modules.multi5x5SuperClustersWithPreshower_cfi import *
from ..modules.muonCSCDigis_cfi import *
from ..modules.muonDTDigis_cfi import *
from ..modules.muonGEMDigis_cfi import *
from ..modules.muonRPCDigis_cfi import *
from ..modules.offlineBeamSpot_cfi import *
from ..modules.offlinePrimaryVertices_cfi import *
from ..modules.offlinePrimaryVerticesWithBS_cfi import *
from ..modules.omtfStage2Digis_cfi import *
from ..modules.onlineMetaDataDigis_cfi import *
from ..modules.particleFlowBadHcalPseudoCluster_cfi import *
from ..modules.particleFlowBlock_cfi import *
from ..modules.particleFlowClusterECAL_cfi import *
from ..modules.particleFlowClusterECALUncorrected_cfi import *
from ..modules.particleFlowClusterHBHE_cfi import *
from ..modules.particleFlowClusterHCAL_cfi import *
from ..modules.particleFlowClusterHF_cfi import *
from ..modules.particleFlowClusterHGCal_cfi import *
from ..modules.particleFlowClusterHGCalFromMultiCl_cfi import *
from ..modules.particleFlowClusterHO_cfi import *
from ..modules.particleFlowClusterPS_cfi import *
from ..modules.particleFlowRecHitECAL_cfi import *
from ..modules.particleFlowRecHitHBHE_cfi import *
from ..modules.particleFlowRecHitHF_cfi import *
from ..modules.particleFlowRecHitHGC_cfi import *
from ..modules.particleFlowRecHitHO_cfi import *
from ..modules.particleFlowRecHitPS_cfi import *
from ..modules.particleFlowSuperClusterECAL_cfi import *
from ..modules.particleFlowSuperClusterHGCal_cfi import *
from ..modules.particleFlowSuperClusterHGCalFromMultiCl_cfi import *
from ..modules.particleFlowTimeAssignerECAL_cfi import *
from ..modules.particleFlowTmp_cfi import *
from ..modules.particleFlowTmpBarrel_cfi import *
from ..modules.pfTICL_cfi import *
from ..modules.pfTrack_cfi import *
from ..modules.pixelFitterByHelixProjections_cfi import *
from ..modules.pixelTrackFilterByKinematics_cfi import *
from ..modules.pixelTracks_cfi import *
from ..modules.pixelTracksHitDoublets_cfi import *
from ..modules.pixelTracksHitSeeds_cfi import *
from ..modules.pixelTracksSeedLayers_cfi import *
from ..modules.pixelTracksTrackingRegions_cfi import *
from ..modules.pixelVertices_cfi import *
from ..modules.rpcCPPFRawToDigi_cfi import *
from ..modules.rpcTwinMuxRawToDigi_cfi import *
from ..modules.scalersRawToDigi_cfi import *
from ..modules.siPhase2Clusters_cfi import *
from ..modules.siPixelClusters_cfi import *
from ..modules.siPixelClusterShapeCache_cfi import *
from ..modules.siPixelClustersPreSplitting_cfi import *
from ..modules.siPixelRecHits_cfi import *
from ..modules.siPixelRecHitsPreSplitting_cfi import *
from ..modules.siStripDigis_cfi import *
from ..modules.tcdsDigis_cfi import *
from ..modules.ticlLayerTileProducer_cfi import *
from ..modules.ticlMultiClustersFromTrackstersEM_cfi import *
from ..modules.ticlMultiClustersFromTrackstersHAD_cfi import *
from ..modules.ticlMultiClustersFromTrackstersMerge_cfi import *
from ..modules.ticlMultiClustersFromTrackstersTrk_cfi import *
from ..modules.ticlMultiClustersFromTrackstersTrkEM_cfi import *
from ..modules.ticlSeedingGlobal_cfi import *
from ..modules.ticlSeedingTrk_cfi import *
from ..modules.ticlTrackstersEM_cfi import *
from ..modules.ticlTrackstersHAD_cfi import *
from ..modules.ticlTrackstersMerge_cfi import *
from ..modules.ticlTrackstersTrk_cfi import *
from ..modules.ticlTrackstersTrkEM_cfi import *
from ..modules.totemRPRawToDigi_cfi import *
from ..modules.totemTimingRawToDigi_cfi import *
from ..modules.totemTriggerRawToDigi_cfi import *
from ..modules.towerMaker_cfi import *
from ..modules.towerMakerWithHO_cfi import *
from ..modules.trackerClusterCheck_cfi import *
from ..modules.trackRefsForJetsBeforeSorting_cfi import *
from ..modules.trackVertexArbitrator_cfi import *
from ..modules.trackWithVertexRefSelectorBeforeSorting_cfi import *
from ..modules.twinMuxStage2Digis_cfi import *
from ..modules.uncleanedHybridSuperClusters_cfi import *
from ..modules.uncleanedOnlyCorrectedHybridSuperClusters_cfi import *
from ..modules.uncleanedOnlyCorrectedMulti5x5SuperClustersWithPreshower_cfi import *
from ..modules.uncleanedOnlyMulti5x5SuperClustersWithPreshower_cfi import *
from ..modules.unsortedOfflinePrimaryVertices_cfi import *
from ..modules.vertexMerger_cfi import *
from ..modules.zdcreco_cfi import *

HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4 = cms.Path(l1tPFPuppiHT400offMaxEta2p4+l1t1PFPuppiJet70offMaxEta2p4+l1t2PFPuppiJet55offMaxEta2p4+l1t4PFPuppiJet40offMaxEta2p4+l1t4PFPuppiJet25OnlineMaxEta2p4+goodOfflinePrimaryVertices+hltPFPuppiCentralJetQuad30MaxEta2p4+hlt1PFPuppiCentralJet70MaxEta2p4+hlt2PFPuppiCentralJet40MaxEta2p4+hltPFPuppiCentralJetsQuad30HT200MaxEta2p4+hltPFPuppiJetForBtagSelectorEta2p4+hltBTagPFPuppiDeepFlavour0p375Eta2p4TripleEta2p4, cms.Task(HGCalRecHit, HGCalUncalibRecHit, MeasurementTrackerEvent, ak4CaloJetsForTrk, bmtfDigis, bunchSpacingProducer, caloLayer1Digis, caloStage1Digis, caloStage1FinalDigis, caloStage1LegacyFormatDigis, caloStage2Digis, caloTowerForTrk, cleanedHybridSuperClusters, clusterSummaryProducer, correctedHybridSuperClusters, correctedMulti5x5SuperClustersWithPreshower, csctfDigis, ctppsDiamondRawToDigi, ctppsPixelDigis, dttfDigis, ecalBarrelClusterFastTimer, ecalCompactTrigPrim, ecalDetIdToBeRecovered, ecalDetailedTimeRecHit, ecalDigis, ecalMultiFitUncalibRecHit, ecalPreshowerDigis, ecalPreshowerRecHit, ecalRecHit, ecalTPSkim, emtfStage2Digis, filteredLayerClustersEM, filteredLayerClustersHAD, filteredLayerClustersTrk, filteredLayerClustersTrkEM, firstStepPrimaryVertices, firstStepPrimaryVerticesUnsorted, fixedGridRhoFastjetAllTmp, gctDigis, generalTracks, gmtStage2Digis, gtDigis, gtStage2Digis, hbhereco, hcalDigis, hfprereco, hfreco, hgcalDigis, hgcalLayerClusters, hgcalMultiClusters, hgcalTrackCollection, highPtTripletStepClusters, highPtTripletStepHitDoublets, highPtTripletStepHitTriplets, highPtTripletStepSeedLayers, highPtTripletStepSeeds, highPtTripletStepTrackCandidates, highPtTripletStepTrackCutClassifier, highPtTripletStepTrackSelectionHighPurity, highPtTripletStepTrackingRegions, highPtTripletStepTracks, hltAK4CaloJets, hltCsc2DRecHits, hltCscSegments, hltDt1DRecHits, hltDt4DSegments, hltGemRecHits, hltGemSegments, hltIter0Phase2L3FromL1TkMuonCkfTrackCandidates, hltIter0Phase2L3FromL1TkMuonCtfWithMaterialTracks, hltIter0Phase2L3FromL1TkMuonPixelSeedsFromPixelTracks, hltIter0Phase2L3FromL1TkMuonTrackCutClassifier, hltIter0Phase2L3FromL1TkMuonTrackSelectionHighPurity, hltIter2Phase2L3FromL1TkMuonCkfTrackCandidates, hltIter2Phase2L3FromL1TkMuonClustersRefRemoval, hltIter2Phase2L3FromL1TkMuonCtfWithMaterialTracks, hltIter2Phase2L3FromL1TkMuonMaskedMeasurementTrackerEvent, hltIter2Phase2L3FromL1TkMuonMerged, hltIter2Phase2L3FromL1TkMuonPixelClusterCheck, hltIter2Phase2L3FromL1TkMuonPixelHitDoublets, hltIter2Phase2L3FromL1TkMuonPixelHitTriplets, hltIter2Phase2L3FromL1TkMuonPixelLayerTriplets, hltIter2Phase2L3FromL1TkMuonPixelSeeds, hltIter2Phase2L3FromL1TkMuonTrackCutClassifier, hltIter2Phase2L3FromL1TkMuonTrackSelectionHighPurity, hltL2MuonFromL1TkMuonCandidates, hltL2MuonSeedsFromL1TkMuon, hltL2MuonsFromL1TkMuon, hltL2OfflineMuonSeeds, hltL3MuonsPhase2L3Links, hltL3MuonsPhase2L3OI, hltMe0RecHits, hltMe0Segments, hltPhase2L3FromL1TkMuonPixelLayerQuadruplets, hltPhase2L3FromL1TkMuonPixelTracks, hltPhase2L3FromL1TkMuonPixelTracksHitDoublets, hltPhase2L3FromL1TkMuonPixelTracksHitQuadruplets, hltPhase2L3FromL1TkMuonPixelTracksTrackingRegions, hltPhase2L3FromL1TkMuonPixelVertices, hltPhase2L3FromL1TkMuonTrimmedPixelVertices, hltPhase2L3GlbMuon, hltPhase2L3MuonCandidates, hltPhase2L3MuonMerged, hltPhase2L3MuonPixelTracksFilter, hltPhase2L3MuonPixelTracksFitter, hltPhase2L3MuonTracks, hltPhase2L3Muons, hltPhase2L3MuonsNoID, hltPhase2L3OIL3MuonCandidates, hltPhase2L3OIL3Muons, hltPhase2L3OIL3MuonsLinksCombination, hltPhase2L3OIMuCtfWithMaterialTracks, hltPhase2L3OIMuonTrackCutClassifier, hltPhase2L3OIMuonTrackSelectionHighPurity, hltPhase2L3OISeedsFromL2Muons, hltPhase2L3OITrackCandidates, hltRpcRecHits, horeco, hybridSuperClusters, inclusiveSecondaryVertices, inclusiveVertexFinder, initialStepSeeds, initialStepTrackCandidates, initialStepTrackCutClassifier, initialStepTrackRefsForJets, initialStepTrackSelectionHighPurity, initialStepTracks, multi5x5BasicClustersCleaned, multi5x5BasicClustersUncleaned, multi5x5PreshowerClusterShape, multi5x5SuperClusters, multi5x5SuperClustersCleaned, multi5x5SuperClustersUncleaned, multi5x5SuperClustersWithPreshower, muonCSCDigis, muonDTDigis, muonGEMDigis, muonRPCDigis, offlineBeamSpot, offlinePrimaryVertices, offlinePrimaryVerticesWithBS, omtfStage2Digis, onlineMetaDataDigis, particleFlowBadHcalPseudoCluster, particleFlowBlock, particleFlowClusterECAL, particleFlowClusterECALUncorrected, particleFlowClusterHBHE, particleFlowClusterHCAL, particleFlowClusterHF, particleFlowClusterHGCal, particleFlowClusterHGCalFromMultiCl, particleFlowClusterHO, particleFlowClusterPS, particleFlowRecHitECAL, particleFlowRecHitHBHE, particleFlowRecHitHF, particleFlowRecHitHGC, particleFlowRecHitHO, particleFlowRecHitPS, particleFlowSuperClusterECAL, particleFlowSuperClusterHGCal, particleFlowSuperClusterHGCalFromMultiCl, particleFlowTimeAssignerECAL, particleFlowTmp, particleFlowTmpBarrel, pfTICL, pfTrack, pixelFitterByHelixProjections, pixelTrackFilterByKinematics, pixelTracks, pixelTracksHitDoublets, pixelTracksHitSeeds, pixelTracksSeedLayers, pixelTracksTrackingRegions, pixelVertices, rpcCPPFRawToDigi, rpcTwinMuxRawToDigi, scalersRawToDigi, siPhase2Clusters, siPixelClusterShapeCache, siPixelClusters, siPixelClustersPreSplitting, siPixelRecHits, siPixelRecHitsPreSplitting, siStripDigis, tcdsDigis, ticlLayerTileProducer, ticlMultiClustersFromTrackstersEM, ticlMultiClustersFromTrackstersHAD, ticlMultiClustersFromTrackstersMerge, ticlMultiClustersFromTrackstersTrk, ticlMultiClustersFromTrackstersTrkEM, ticlSeedingGlobal, ticlSeedingTrk, ticlTrackstersEM, ticlTrackstersHAD, ticlTrackstersMerge, ticlTrackstersTrk, ticlTrackstersTrkEM, totemRPRawToDigi, totemTimingRawToDigi, totemTriggerRawToDigi, towerMaker, towerMakerWithHO, trackRefsForJetsBeforeSorting, trackVertexArbitrator, trackWithVertexRefSelectorBeforeSorting, trackerClusterCheck, twinMuxStage2Digis, uncleanedHybridSuperClusters, uncleanedOnlyCorrectedHybridSuperClusters, uncleanedOnlyCorrectedMulti5x5SuperClustersWithPreshower, uncleanedOnlyMulti5x5SuperClustersWithPreshower, unsortedOfflinePrimaryVertices, vertexMerger, zdcreco), cms.Task(hltAK4PFPuppiJetCorrector, hltAK4PFPuppiJetCorrectorL1, hltAK4PFPuppiJetCorrectorL2, hltAK4PFPuppiJetCorrectorL3, hltAK4PFPuppiJets, hltAK4PFPuppiJetsCorrected, hltDeepBLifetimeTagInfosPFPuppiModEta2p4, hltDeepCombinedSecondaryVertexBJetTagsInfosPuppiModEta2p4, hltDeepInclusiveMergedVerticesPF, hltDeepInclusiveSecondaryVerticesPF, hltDeepInclusiveVertexFinderPF, hltDeepSecondaryVertexTagInfosPFPuppiModEta2p4, hltDeepTrackVertexArbitratorPF, hltPFPuppi, hltPFPuppiJetForBtagEta2p4, hltPfDeepFlavourJetTagsModEta2p4, hltPfDeepFlavourTagInfosModEta2p4, hltPixelClustersMultiplicity, hltPrimaryVertexAssociationModEta2p4, l1tPFPuppiHT))
